USE TechShop;

SELECT * FROM Customers;
SELECT * FROM Orders;
SELECT * FROM OrderDetails;
SELECT * FROM Inventory;
SELECT * FROM Products;

/*
Task 4. Subquery and its type:  
1. Write an SQL query to find out which customers have not placed any orders. */
SELECT CustomerID,CONCAT(FirstName,'',LastName) AS CustomerName FROM Customers C
WHERE customerID NOT IN (SELECT customerID FROM Orders);

/*2. Write an SQL query to find the total number of products available for sale. */ 
SELECT (SELECT COUNT(*) FROM Products) AS AvailableSale;

/*3. Write an SQL query to calculate the total revenue generated by TechShop.  */
SELECT (SELECT SUM(OD.Quantity*P.Price) FROM OrderDetails OD JOIN Products P
ON OD.ProductID=P.ProductID) AS TotalRevenue;

/*4. Write an SQL query to calculate the average quantity ordered for products in a specific category. 
Allow users to input the category name as a parameter. */
DECLARE @category VARCHAR(100)='Electronics';

SELECT (SELECT AVG(OD.Quantity) FROM OrderDetails OD JOIN Products P
ON OD.ProductID=P.ProductID WHERE P.Category=@category) AS QuantityOrdered;

/*5. Write an SQL query to calculate the total revenue generated by a specific customer. Allow users 
to input the customer ID as a parameter. */
DECLARE @custId INT=103;

SELECT (SELECT SUM(TotalAmount) FROM Orders WHERE customerID=@custId) AS TotalRevGen

/*6. Write an SQL query to find the customers who have placed the most orders. List their names 
and the number of orders they've placed. */
SELECT TOP 1 FirstName,LastName,OrderCount  
FROM (SELECT C.FirstName,C.LastName,COUNT(O.OrderID) AS OrderCount FROM Customers C 
JOIN Orders O ON C.customerID=O.customerID GROUP BY C.FirstName,C.LastName)
AS CustomerOrders
ORDER BY OrderCount DESC;


/*7. Write an SQL query to find the most popular product category, which is the one with the highest 
total quantity ordered across all orders. */
WITH PopularCategory AS
	(SELECT P.Category ,SUM(OD.Quantity) AS Count FROM Products P
	JOIN OrderDetails OD ON P.ProductID=OD.ProductID
	GROUP BY P.Category )
SELECT Category,Count FROM PopularCategory
WHERE Count = (SELECT MAX(Count) FROM PopularCategory); 

/*8. Write an SQL query to find the customer who has spent the most money (highest total revenue) 
on electronic gadgets. List their name and total spending. */
WITH HighRevCust AS
	(SELECT C.FirstName,C.LastName,SUM(O.TotalAmount) AS Amt FROM Customers C 
	JOIN Orders O ON C.customerID=O.customerID
	JOIN OrderDetails OD ON OD.OrderID=O.OrderID
	JOIN Products P ON P.ProductID=OD.ProductID
	WHERE P.Category='Electronics'
	GROUP BY C.FirstName,C.LastName)
SELECT FirstName, LastName, Amt FROM HighRevCust
WHERE Amt=(SELECT MAX(Amt )FROM HighRevCust);


/*9. Write an SQL query to calculate the average order value (total revenue divided by the number of 
orders) for all customers. */
SELECT (SELECT AVG(TotalAmount) FROM Orders ) AS AvgOrderVal;

/*10. Write an SQL query to find the total number of orders placed by each customer and list their 
names along with the order count.*/
SELECT TotalOrder, CustName FROM 
	(SELECT COUNT(O.OrderID) AS TotalOrder,CONCAT(C.FirstName,' ',C.LastName) AS CustName FROM Orders O 
	JOIN Customers C ON O.customerID=C.customerID GROUP BY CONCAT(C.FirstName,' ',C.LastName))
AS Custorder;